### ISSUE TITLE
Keccak implementations missing when installed from pip

### ISSUE THREAD

**Issue by adityanalge** [Destiner/blocksmith#1]
I installed blocksmith using pip. The following issue arises on trying to import blocksmith in the python3 console using Spyder.

line 3 - ethereum.py

    from Crypto.Hash import keccak

ImportError: cannot import name 'keccak'

**Comment by Destiner** [comment]
Yes, you're right. The `pycryptodome` package was missing. Fixed it.

Latest release (1.2.1) should work.

**Comment by kaankozan** [comment]
sudo python3.6 -m pip install pycryptod
omex


Or 


sudo python3.6 -m pip install pycryptod
ome


This command lines my keccak problem fix it

**Comment by vbooka1** [comment]
note that you also need to replace `from Crypto.Hash import keccak` with `from Cryptodome.Hash import keccak`

**Comment by waveboy800** [comment]
Thanks，the problem was solved
