### ISSUE TITLE
mismatch

### ISSUE THREAD

**Issue by arshiay** [Destiner/blocksmith#2]
hi
when i import private key to blockchain i receive different wallet address which i make by code why?
for example
private key is 5b9fa534aee8f01b8df4242bfd157e920e2b0e7cbd79afa541446aa426223b68
made by code
wallet is 1PsUFe4kVUJixGEmA69fpWpBKdh2SZdwcY 
made by code

but after import to blockchain wallet address is
17BB2XwbhjUc8SYMSvvEkf2UWzpZuZFYvM

**Comment by Destiner** [comment]
Hi, thank you for the patience.

So, this is the same key, but in different forms. `1PsUFe4kVUJixGEmA69fpWpBKdh2SZdwcY` is the long form and `17BB2XwbhjUc8SYMSvvEkf2UWzpZuZFYvM ` is short (or compressed) form.

You can use `BitcoinWallet.generate_compressed_address` to make this short version.
