### ISSUE TITLE
Bitcoin pri key to address problem?

### ISSUE THREAD

**Issue by kaankozan** [Destiner/blocksmith#4]
i dont think bitcoin prikey to address dont true work

Because 

i import in blockchain wallet private key
i see another address

But this code generate another addresd

**Comment by Destiner** [comment]
If you'll have problems with correct generation of wallet, feel free to share your initial private key, I'll look into it.
Also, you can cross validate wallet by using https://www.bitaddress.org ("Wallet Details" tab).
